export const pages = [
  {
    id: "home",
    label: "ホーム",
    mockup: "/mockups/home.png",
    description: "NemuNoteの価値を伝えるファーストビューと主要導線のページ。",
    hotspots: [
      { id: "nav-features", label: "機能へ", target: "features", x: 48.5, y: 5.0, w: 5.8, h: 3.8 },
      { id: "nav-report", label: "レポートへ", target: "report", x: 55.4, y: 5.0, w: 6.2, h: 3.8 },
      { id: "nav-pricing", label: "料金へ", target: "pricing", x: 62.7, y: 5.0, w: 5.8, h: 3.8 },
      { id: "nav-voices", label: "利用者の声へ", target: "voices", x: 69.7, y: 5.0, w: 7.0, h: 3.8 },
      { id: "nav-guide", label: "使い方へ", target: "guide", x: 78.0, y: 5.0, w: 5.5, h: 3.8 },
      { id: "nav-download", label: "ダウンロードへ", target: "download", x: 85.4, y: 3.9, w: 10.5, h: 5.8 },
      { id: "hero-cta-primary", label: "無料で始める", target: "download", x: 10.5, y: 63.0, w: 15.8, h: 7.5 },
      { id: "hero-cta-secondary", label: "睡眠レポートを見る", target: "report", x: 28.2, y: 63.0, w: 16.8, h: 7.5 },
    ],
  },
  {
    id: "features",
    label: "機能",
    mockup: "/mockups/features.png",
    description: "睡眠記録、メモ、習慣化支援などの主要機能を紹介するページ。",
    hotspots: [
      { id: "nav-home", label: "ホームへ", target: "home", x: 6.0, y: 4.4, w: 12.0, h: 5.0 },
      { id: "nav-report", label: "レポートへ", target: "report", x: 55.4, y: 5.0, w: 6.2, h: 3.8 },
      { id: "nav-pricing", label: "料金へ", target: "pricing", x: 62.7, y: 5.0, w: 5.8, h: 3.8 },
      { id: "nav-guide", label: "使い方へ", target: "guide", x: 78.0, y: 5.0, w: 5.5, h: 3.8 },
      { id: "nav-download", label: "ダウンロードへ", target: "download", x: 85.4, y: 3.9, w: 10.5, h: 5.8 },
      { id: "feature-report-cta", label: "レポート機能を見る", target: "report", x: 68.5, y: 72.0, w: 18.0, h: 7.0 },
    ],
  },
  {
    id: "report",
    label: "レポート",
    mockup: "/mockups/report.png",
    description: "睡眠傾向の可視化と週次レポート体験を説明するページ。",
    hotspots: [
      { id: "nav-home", label: "ホームへ", target: "home", x: 6.0, y: 4.4, w: 12.0, h: 5.0 },
      { id: "nav-features", label: "機能へ", target: "features", x: 48.5, y: 5.0, w: 5.8, h: 3.8 },
      { id: "nav-pricing", label: "料金へ", target: "pricing", x: 62.7, y: 5.0, w: 5.8, h: 3.8 },
      { id: "nav-download", label: "ダウンロードへ", target: "download", x: 85.4, y: 3.9, w: 10.5, h: 5.8 },
      { id: "report-cta-pricing", label: "料金を見る", target: "pricing", x: 11.5, y: 75.0, w: 14.5, h: 6.5 },
      { id: "report-cta-guide", label: "使い方を見る", target: "guide", x: 28.0, y: 75.0, w: 14.5, h: 6.5 },
    ],
  },
  {
    id: "pricing",
    label: "料金",
    mockup: "/mockups/pricing.png",
    description: "無料プランとプレミアムプランの違いを比較するページ。",
    hotspots: [
      { id: "nav-home", label: "ホームへ", target: "home", x: 6.0, y: 4.4, w: 12.0, h: 5.0 },
      { id: "nav-features", label: "機能へ", target: "features", x: 48.5, y: 5.0, w: 5.8, h: 3.8 },
      { id: "nav-voices", label: "利用者の声へ", target: "voices", x: 69.7, y: 5.0, w: 7.0, h: 3.8 },
      { id: "nav-download", label: "ダウンロードへ", target: "download", x: 85.4, y: 3.9, w: 10.5, h: 5.8 },
      { id: "pricing-free-cta", label: "無料で始める", target: "download", x: 24.0, y: 71.5, w: 15.5, h: 6.8 },
      { id: "pricing-premium-cta", label: "プレミアムを試す", target: "download", x: 59.5, y: 71.5, w: 16.5, h: 6.8 },
    ],
  },
  {
    id: "voices",
    label: "利用者の声",
    mockup: "/mockups/voices.png",
    description: "NemuNote利用者の感想と利用シーンを掲載するページ。",
    hotspots: [
      { id: "nav-home", label: "ホームへ", target: "home", x: 6.0, y: 4.4, w: 12.0, h: 5.0 },
      { id: "nav-features", label: "機能へ", target: "features", x: 48.5, y: 5.0, w: 5.8, h: 3.8 },
      { id: "nav-pricing", label: "料金へ", target: "pricing", x: 62.7, y: 5.0, w: 5.8, h: 3.8 },
      { id: "nav-guide", label: "使い方へ", target: "guide", x: 78.0, y: 5.0, w: 5.5, h: 3.8 },
      { id: "nav-download", label: "ダウンロードへ", target: "download", x: 85.4, y: 3.9, w: 10.5, h: 5.8 },
      { id: "voices-cta-guide", label: "使い方を見る", target: "guide", x: 40.5, y: 78.0, w: 18.5, h: 6.8 },
    ],
  },
  {
    id: "guide",
    label: "使い方",
    mockup: "/mockups/guide.png",
    description: "アプリ導入から毎日の記録、振り返りまでの流れを案内するページ。",
    hotspots: [
      { id: "nav-home", label: "ホームへ", target: "home", x: 6.0, y: 4.4, w: 12.0, h: 5.0 },
      { id: "nav-features", label: "機能へ", target: "features", x: 48.5, y: 5.0, w: 5.8, h: 3.8 },
      { id: "nav-faq", label: "よくある質問へ", target: "faq", x: 74.0, y: 84.0, w: 15.0, h: 6.0 },
      { id: "nav-download", label: "ダウンロードへ", target: "download", x: 85.4, y: 3.9, w: 10.5, h: 5.8 },
      { id: "guide-step-download", label: "アプリを入手", target: "download", x: 12.0, y: 70.5, w: 17.0, h: 7.0 },
      { id: "guide-step-report", label: "記録を振り返る", target: "report", x: 71.0, y: 70.5, w: 17.0, h: 7.0 },
    ],
  },
  {
    id: "faq",
    label: "よくある質問",
    mockup: "/mockups/faq.png",
    description: "利用開始前の疑問、料金、データ管理に関する質問をまとめたページ。",
    hotspots: [
      { id: "nav-home", label: "ホームへ", target: "home", x: 6.0, y: 4.4, w: 12.0, h: 5.0 },
      { id: "nav-guide", label: "使い方へ", target: "guide", x: 78.0, y: 5.0, w: 5.5, h: 3.8 },
      { id: "nav-download", label: "ダウンロードへ", target: "download", x: 85.4, y: 3.9, w: 10.5, h: 5.8 },
      { id: "faq-pricing-link", label: "料金について", target: "pricing", x: 15.0, y: 34.0, w: 70.0, h: 7.0 },
      { id: "faq-privacy-link", label: "データ管理について", target: "privacy", x: 15.0, y: 56.5, w: 70.0, h: 7.0 },
      { id: "faq-download-cta", label: "まずは無料で始める", target: "download", x: 39.5, y: 82.0, w: 21.0, h: 7.0 },
    ],
  },
  {
    id: "download",
    label: "ダウンロード",
    mockup: "/mockups/download.png",
    description: "App StoreとGoogle Playへの導線を集約するダウンロードページ。",
    hotspots: [
      { id: "nav-home", label: "ホームへ", target: "home", x: 6.0, y: 4.4, w: 12.0, h: 5.0 },
      { id: "nav-features", label: "機能へ", target: "features", x: 48.5, y: 5.0, w: 5.8, h: 3.8 },
      { id: "nav-faq", label: "よくある質問へ", target: "faq", x: 68.2, y: 83.5, w: 14.0, h: 5.8 },
      { id: "download-app-store", label: "App Store", target: "download", x: 14.0, y: 59.5, w: 16.0, h: 7.5 },
      { id: "download-google-play", label: "Google Play", target: "download", x: 32.0, y: 59.5, w: 16.0, h: 7.5 },
      { id: "download-privacy", label: "プライバシーポリシー", target: "privacy", x: 38.5, y: 83.5, w: 18.5, h: 5.8 },
    ],
  },
  {
    id: "privacy",
    label: "プライバシー",
    mockup: "/mockups/privacy.png",
    description: "睡眠データと個人情報の取り扱い方針を説明するページ。",
    hotspots: [
      { id: "nav-home", label: "ホームへ", target: "home", x: 6.0, y: 4.4, w: 12.0, h: 5.0 },
      { id: "nav-faq", label: "よくある質問へ", target: "faq", x: 66.0, y: 5.0, w: 8.0, h: 3.8 },
      { id: "nav-download", label: "ダウンロードへ", target: "download", x: 85.4, y: 3.9, w: 10.5, h: 5.8 },
      { id: "privacy-contact", label: "お問い合わせ", target: "faq", x: 14.0, y: 78.5, w: 17.0, h: 6.5 },
      { id: "privacy-start", label: "NemuNoteを始める", target: "download", x: 33.0, y: 78.5, w: 19.0, h: 6.5 },
    ],
  },
];

export const pageMap = Object.fromEntries(pages.map((page) => [page.id, page]));
